{% set name = "diffpy.srfit" %}
{% set version = "3.3.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/diffpy_srfit/diffpy_srfit-{{ version }}.tar.gz
  sha256: 5e146a0e0eb3780a85ad2824d567707ee1d4e60b6028f819046045884d1be16f

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    -  diffpy.srfit = diffpy.srfit.srfit_app:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - scipy

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - sympy
  source_files:
    - tests

  commands:
    - pip check
    - pytest

about:
  home: https://github.com/diffpy/diffpy.srfit/
  summary: Generalized code base for modeling problems.
  license: LicenseRef-diffpy
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    The diffpy.srfit package provides the framework for building a global 
    optimizer on the fly from components such as function calculators 
    (that calculate different data spectra), regression algorithms and 
    structure models. The software is capable of co-refinement using 
    multiple information sources or models. It provides a uniform interface 
    for various regression algorithms. The target function being optimized 
    can be specified by the user according to the data available.
  doc_url: http://www.diffpy.org/diffpy.srfit/
  dev_url: https://github.com/diffpy/diffpy.srfit

extra:
  recipe-maintainers:
    - sbillinge
    - cadenmyers13
