{% set name = "diffpy.srfit" %}
{% set version = "3.3.1" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/d/diffpy_srfit/diffpy_srfit-{{ version }}.tar.gz
  sha256: 9cff8ac3a9658c0975e74dfbe95ee2c79bf3652fd20be1905c2efd075a766e47

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - diffpy.srfit = diffpy.srfit.srfit_app:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - scipy
    - bg-mpl-stylesheets
    - diffpy.utils
    - diffpy.structure

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - sympy
  source_files:
    - tests

  commands:
    - pip check
    - pytest

about:
  home: https://github.com/diffpy/diffpy.srfit/
  summary: Open source (the license is 100% compatible with bsd-3 clause) code base for modeling problems.
  license: LicenseRef-diffpy
  license_file: LICENSE.rst
  description: |
    The diffpy.srfit package provides the framework for building a global 
    optimizer on the fly from components such as function calculators 
    (that calculate different data spectra), regression algorithms and 
    structure models. The software is capable of co-refinement using 
    multiple information sources or models. It provides a uniform interface 
    for various regression algorithms. The target function being optimized 
    can be specified by the user according to the data available.
  doc_url: http://www.diffpy.org/diffpy.srfit/
  dev_url: https://github.com/diffpy/diffpy.srfit

extra:
  recipe-maintainers:
    - sbillinge
    - cadenmyers13
    - Tieqiong
